import { lazy } from 'react'

export const Home = lazy(() => import('~/pages/Home'))
export const ProductList = lazy(() => import('~/pages/ProductList'))
export const ProductDetail = lazy(() => import('~/pages/ProductDetail'))
export const Cart = lazy(() => import('~/pages/Cart'))
export const NotFound = lazy(() => import('~/pages/NotFound'))
export const Register = lazy(() => import('~/pages/Register'))
export const Login = lazy(() => import('~/pages/Login'))
export const Profile = lazy(() => import('~/pages/UserProfile/components/Profile'))
export const ChangePassword = lazy(() => import('~/pages/UserProfile/components/ChangePassword'))
export const Order = lazy(() => import('~/pages/UserProfile/components/Order'))
export const Notification = lazy(() => import('~/pages/UserProfile/components/Notification'))
export const VerifyEmail = lazy(() => import('~/pages/VerifyEmail'))
export const ForgotPassword = lazy(() => import('~/pages/ForgotPassword'))
export const ResetPassword = lazy(() => import('~/pages/ResetPassword'))
export const Dashboard = lazy(() => import('~/pages/Admin/pages/Dashboard'))
export const ProductAdmin = lazy(() => import('~/pages/Admin/pages/ProductAdmin'))
export const CategoryAdmin = lazy(() => import('~/pages/Admin/pages/CategoryAdmin'))
export const OrderAdmin = lazy(() => import('~/pages/Admin/pages/OrderAdmin'))
export const NotificationAdmin = lazy(() => import('~/pages/Admin/pages/NotificationAdmin'))
export const UserAdmin = lazy(() => import('~/pages/Admin/pages/UserAdmin'))
export const RoleManager = lazy(() => import('~/pages/Admin/pages/RoleManager'))
