server {    
  listen 80;
  listen [::]:80;

  root /var/www/nest-shop.vannghia.online/html;
  index index.html index.htm index.nginx-debian.html;

  server_name nest-shop.vannghia.online www.nest-shop.vannghia.online;

  location / {
    try_files $uri /index.html;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}