services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CLIENT_URL=nest-shop.vannghia.online
    ports:
      - 4000:4000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ~/../../var/www/nest-shop.vannghia.online/html:/frontend/dist
    environment:
      - VITE_API_URL=backend:4000
